services:
  ollama:
    image: julianbierbaum/repo:ollama-gemma
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - zotter-network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  next-app:
    image: julianbierbaum/repo:next-app
    ports:
      - "3000:3000"
    networks:
      - zotter-network
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
      - APP_PASSWORD=password
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  zotter-network: