services:
  ollama:
    image: julianbierbaum/repo:ollama-gemma
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  next-app:
    image: julianbierbaum/repo:next-app
    ports:
      - "3002:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
      - APP_PASSWORD=password
    restart: unless-stopped

volumes:
  ollama_data: