services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - zotter-network
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
  
  next-app:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - zotter-network
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama_data:

networks:
  zotter-network: