services:
  next-app:
    image: julianbierbaum/repo:pdf-analyser
    ports:
      - "3002:3000"
    environment:
    - APP_PASSWORD=password
    - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
